### ISSUE TITLE
Missing option to create file from template

### ISSUE THREAD

**Issue by rmvz3** [samdods/Stencil#2]
Hi. I'm trying to test your plugin but, after creating a new template, I can't create a new file because the "New file from custom template" item don't appears among the menu options (I just get a duplicate "New file" instead)

![captura 2015-05-08 a las 2 59 46](https://cloud.githubusercontent.com/assets/674750/7528792/2f4b2218-f52e-11e4-8bfa-5629809130c1.png)

I've restarted Xcode, uninstalled and reinstalled Stencil with no luck.

Using Xcode (v6.3.1). Stencil installed using Alcatraz.

EDIT: The custom template have been created and saved into its folder in the current project.

Thx

**Comment by samdods** [comment]
Wow that's strange. Thanks for trying it out, I'll investigate and get back to you!

**Comment by samdods** [comment]
fixed

**Comment by rmvz3** [comment]
Cool. Works fine now. Thanks
