### ISSUE TITLE
[Feature request] Create template with more than 1 file

### ISSUE THREAD

**Issue by frodella-daitan** [samdods/Stencil#3]
Hi there, first of all this is an awesome plugin, thanks for creating it!

I'm working on an app using the VIPER architecture (http://www.objc.io/issue-13/viper.html) and every "module" always contains the same related classes:

![screen shot 2015-05-08 at 8 56 14 am](https://cloud.githubusercontent.com/assets/7428464/7535898/79d6f852-f560-11e4-81e5-e9430bec8c8b.png)

Would it be possible to extend the plugin so that I could create a template from the whole group, and later create new groups based on that template?

**Comment by samdods** [comment]
sounds like a good addition, i'll see what i can do!

**Comment by samdods** [comment]
latest update supports this, please let me know how you get on with it :) https://twitter.com/dodsios

**Comment by frodella-daitan** [comment]
Worked perfectly, thank you so much for this! :)
