### ISSUE TITLE
Crash under Xcode 6.4 beta

### ISSUE THREAD

**Issue by tonyarnold** [samdods/Stencil#4]
You'll need to wait to add menu items until after the `NSApplicationDidFinishLaunchingNotification` notification fires, otherwise the menus are nil (and your deallocation observer code crashes because it tries to associate `nil` with the object.

**Comment by samdods** [comment]
thanks for spotting! it's now fixed to work with xcode 6.4, let me know how you get on :) https://twitter.com/dodsios
