### ISSUE TITLE
[Question] Do xcode groups need to be in a folder before you can create a template?

### ISSUE THREAD

**Issue by mjjimenez** [samdods/Stencil#5]
I had some trouble trying to create templates with interface builder files just like in the blog post. It wasn't until I put all the files into a folder and assigned the group to that folder that I had success. Is this the desired process in order to create template groups? If it is, I think it would be better if you could mention that in the blog post as well. 

It would be great if it could function the same way without having to assign the group into a folder though.

**Comment by samdods** [comment]
That is intended functionality, but I'm gonna change it so that you can create from selected files, then there becomes no issue of groups or folders.

**Comment by samdods** [comment]
latest update has modified functionality, you create template from selected files instead of from project group. please let me know how you get on :) https://twitter.com/dodsios
