### ISSUE TITLE
Transfer templates to different Mac

### ISSUE THREAD

**Issue by mjjimenez** [samdods/Stencil#9]
Hi. I was wondering if you have any advice on how to transfer the templates to a different Mac. I'm looking transfer some templates to my work Mac. 

Thanks!

**Comment by samdods** [comment]
Do you have the templates within an Xcode project? The templates are stored as files, so just transfer them however you would transfer any other files, and save them in the same directory relative to the project you're working on. Don't you commit your code to a remote repository? If so, the templates will also be in the repo, so they will be available when you clone the repo on the other Mac.

**Comment by mjjimenez** [comment]
For some reason, I had the mistaken idea that the templates were stored in a Stencil plugin directory on the Mac. Thanks for clarifying things for me.
